version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: '/' # Location of package.json
    schedule:
      interval: 'weekly'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"